# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('use_count', models.IntegerField(default=0)),
                ('creation_time', models.TimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=1)),
            ],
        ),
    ]
