# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='creation_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
