# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180903_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='creation_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='creation_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
