# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181021_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='description',
        ),
    ]
