# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_thread_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='created_by',
        ),
    ]
