# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_thread_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ForumUser'),
        ),
    ]
