# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181023_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='creation_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
