# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20181023_2306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thread',
            new_name='Post',
        ),
    ]
