# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20181024_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='app.Tag'),
        ),
    ]
