# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20181025_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(null=True, to='app.Tag'),
        ),
    ]
