# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20181025_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
