# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20181029_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvote_count',
        ),
        migrations.AddField(
            model_name='post',
            name='voters',
            field=models.ManyToManyField(to='app.ForumUser'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abccdd', to='app.ForumUser'),
        ),
    ]
