# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20181029_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
        migrations.AddField(
            model_name='post',
            name='viewers',
            field=models.ManyToManyField(related_name='viewed_post', to='app.ForumUser'),
        ),
    ]
