# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20181029_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='voters',
        ),
        migrations.RemoveField(
            model_name='post',
            name='voters',
        ),
        migrations.AddField(
            model_name='answer',
            name='down_voters',
            field=models.ManyToManyField(related_name='down_voted_answer', to='app.ForumUser'),
        ),
        migrations.AddField(
            model_name='answer',
            name='up_voters',
            field=models.ManyToManyField(related_name='up_voted_answer', to='app.ForumUser'),
        ),
        migrations.AddField(
            model_name='post',
            name='down_voters',
            field=models.ManyToManyField(related_name='down_voted_post', to='app.ForumUser'),
        ),
        migrations.AddField(
            model_name='post',
            name='up_voters',
            field=models.ManyToManyField(related_name='up_voted_post', to='app.ForumUser'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='app.Tag'),
        ),
    ]
