# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20181029_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='accepted',
        ),
        migrations.AddField(
            model_name='post',
            name='accepted_answer',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_answer', to='app.Answer'),
        ),
    ]
