# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20181110_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='accepted_answer',
        ),
    ]
