# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_remove_post_accepted_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='accepted_answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_answer', to='app.Answer'),
        ),
    ]
