# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_post_accepted_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='accepted_answer',
        ),
    ]
